---
# These variables will be overwrite by terraform
WEBSITE_NAME: "localwebsite"
DB_HOSTNAME: "localhost"
DB_NAME: "wordpress"
DB_USERNAME: "root"
DB_PASSWORD: ""

website_name: "{{ WEBSITE_NAME }}"
wordpress_dir: /var/www
WORDPRESS_VERSION: "latest" 
wordpress_url: http://wordpress.org/wordpress-{{ WORDPRESS_VERSION }}.tar.gz
connections: 1024

db_hostname: "{{ DB_HOSTNAME }}" 
db_name: "{{ DB_NAME }}"
db_username: "{{ DB_USERNAME }}"
db_password: "{{ DB_PASSWORD }}"